NODE_BIN=./node_modules/.bin
DIFF_COVER_BASE_BRANCH=master

.PHONY: clean help migrate prod_requirements quality requirements serve static test validate

help:
	@echo "Please use \`make <target>\` where <target> is one of"
	@echo "  clean                      delete generated byte code and coverage reports"
	@echo "  help                       display this help message"
	@echo "  migrate                    apply database migrations"
	@echo "  prod_requirements          install production requirements for TLM python3 environment"
	@echo "  quality                    check code quality for TLM"
	@echo "  requirements               install local requirements for TLM python3 environment"
	@echo "  serve                      serve TLM App at 0.0.0.0:4444"
	@echo "  static                     build and compress static assets"
	@echo "  test                       run tests"
	@echo "  html_coverage              open code coverage in browser as HTML document"
	@echo "  validate                   check code quality and run tests"
	@echo ""

clean:
	find . -name '*.pyc' -delete
	coverage erase

requirements:
	pip install -qr requirements/local.txt --exists-action w

prod_requirements:
	pip install -qr requirements/production.txt --exists-action w

static:
	python manage.py collectstatic --noinput

serve:
	python manage.py runserver 0.0.0.0:4444

migrate:
	python manage.py migrate --noinput

quality: ## Run pep8 and Pylint
	isort --check-only --diff --recursive tlm/
	pycodestyle --config=.pep8 tlm
	pydocstyle --config=.pep8 tlm

test: clean
	pytest --cov=tlm --cov-report term --cov-config=.coveragerc

html_coverage: ## Generate and view HTML coverage report
	coverage html && open htmlcov/index.html

validate: quality test
